from __future__ import annotations

# ruff: noqa: F401
from .classification import (
    build_classification_plan,
    classification_plan_to_report_item,
    count_plan_statuses,
    execute_classification_plan,
    find_novel_files,
    load_classification_report,
    plan_status_label,
    revise_classification_plan,
    undo_classification_report,
    unique_target_path,
    validate_classification_root,
    write_classification_report,
)
from .constants import *
from .files import (
    decode_bytes,
    file_fingerprint,
    file_quick_signature,
    find_duplicate_files,
    http_bytes,
    http_json,
    is_image_zip_member,
    match_custom_rule,
    pick_archive_cover_name,
    read_archive_cover_bytes,
    read_book_identity,
    read_epub_book_identity,
    read_epub_cover_bytes,
    read_epub_identity_hint,
    read_identity_hint,
    read_local_cover_bytes,
    read_text_identity_hint,
    read_zip_member,
    resolve_zip_member,
    validate_https_url,
    xml_local_name,
)
from .identity import (
    identity_from_filename,
    language_display_name,
    merge_book_identities,
    normalize_identity_values,
    volume_display_name,
    with_series_name,
)
from .metadata import (
    SeriesResolver,
    bangumi_cover_url,
    bangumi_identity_from_item,
    bangumi_infobox_values,
    bangumi_metadata_from_item,
    bangumi_search_items,
    bangumi_subject_url,
    bangumi_tags,
    bangumi_title_candidates,
    clean_summary,
    flatten_bangumi_value,
    item_matches_volume,
    score_bangumi_item_for_detail,
    suggest_renamed_filename,
    unique_existing,
)
from .models import (
    AppSettings,
    BookIdentity,
    BookMetadata,
    ClassificationPlan,
    CustomRule,
    ResolveResult,
)
from .parsing import (
    acceptance_threshold,
    clean_file_stem,
    collapse_spaces,
    contains_cjk,
    extract_book_lookup_query,
    extract_series_guess,
    html_to_text,
    identity_query_for_path,
    infer_language,
    is_noise_tag,
    normalize_for_match,
    normalize_language_code,
    parse_volume_number,
    safe_folder_name,
    score_title,
    strip_bracket_noise,
    strip_release_words,
    title_has_volume,
    weak_file_name_query,
)
from .storage import (
    PersistentMetadataCache,
    app_data_dir,
    app_settings_from_dict,
    app_settings_to_dict,
    book_identity_from_dict,
    book_identity_to_dict,
    book_metadata_from_dict,
    book_metadata_to_dict,
    get_persistent_metadata_cache,
    load_app_settings,
    metadata_cache_path,
    read_json_bounded,
    resolve_result_from_dict,
    resolve_result_to_dict,
    save_app_settings,
    settings_path,
    try_save_app_settings,
    write_json_atomic,
)
